apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: django-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /health/  # Set the desired health check endpoint here
