apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.django.appName }}
  labels:
    app: {{ .Values.django.appName }}
spec:
  replicas: {{ .Values.django.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.django.appName }}  # Change 'pod' to 'app' for consistency
  template:
    metadata:
      labels:
        app: {{ .Values.django.appName }}  # Change 'pod' to 'app' for consistency
    spec:
      containers:
        - name: {{ .Values.django.appName }}
          image: {{ .Values.django.image.repository }}:{{ .Values.django.image.tag }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
          resources:
            requests:
              memory: {{ .Values.django.resources.requests.memory }}
              cpu: {{ .Values.django.resources.requests.cpu }}
            limits:
              memory: {{ .Values.django.resources.limits.memory }}
              cpu: {{ .Values.django.resources.limits.cpu }}
          livenessProbe:
            httpGet:
                path: /health/
                port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
                path: /health/
                port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
            successThreshold: 1
