apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: better-backend-app-django
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: "gke-ingress-static-ip"  # Optional: For a static IP, create one in GCP and replace here
    networking.gke.io/managed-certificates: "gke-openssl-cert"  # Use this for GKE-managed certificates
    kubernetes.io/ingress.allow-http: "false"  # Force HTTPS
    
spec:
  ingressClassName: "gce"  # This replaces the deprecated kubernetes.io/ingress.class annotation
  rules:
  - host: api-v2.integration-betteropinions.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: better-backend-app-django
            port:
              number: 80
