apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.django.appName }}
  labels:
    app: {{ .Values.django.appName }}
  annotations:
    cloud.google.com/backend-config: '{"default": "django-backend-config"}'
spec:
  type: ClusterIP      
  selector:
    app: {{ .Values.django.appName }}
  ports:
    - port: 80
      targetPort: 8000