name: Deploy Django Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: bo-stage
  GKE_CLUSTER: be-demo
  GKE_ZONE: asia-south1
  DEPLOYMENT_NAME: backend-application

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # Configure GKE credentials
      - name: Configure GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Helm Setup
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0'

      # Set Environment-Specific Variables
      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          fi

      # Docker Login
      - name: Login to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: asia-south1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      # Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/bo-main/backend:${{ github.sha }}

      # Scan Docker Image
      - name: Scan Docker image
        uses: anchore/scan-action@v3
        with:
          image: "asia-south1-docker.pkg.dev/${{ env.PROJECT_ID }}/bo-main/backend:${{ github.sha }}"
          fail-build: false
          severity-cutoff: critical

      # Generate TLS Certificate and Secret
      - name: Generate TLS Certificate
        run: |
          mkdir -p ssl
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout ssl/tls.key -out ssl/tls.crt \
            -subj "/CN=api-v2.integration-betteropinions.com"

      - name: Create TLS Secret
        run: |
          kubectl create secret tls gke-openssl-cert \
            --cert=ssl/tls.crt \
            --key=ssl/tls.key \
            --dry-run=client -o yaml | kubectl apply -f -

      # Check and clean up existing release
      - name: Check and clean up existing release
        run: |
          if helm status ${{ env.DEPLOYMENT_NAME }} 2>/dev/null | grep -q 'STATUS: pending-install\|STATUS: pending-upgrade'; then
            echo "Release is in a pending state. Attempting to delete..."
            helm delete ${{ env.DEPLOYMENT_NAME }} --no-hooks || true
            sleep 30  # Wait for resources to be cleaned up
          fi

      # Validate Helm chart
      - name: Validate Helm chart
        run: helm lint ./manifest

      # Deploy Django Application with Helm
      - name: Deploy Django Application
        run: |
          for i in {1..3}; do
            helm template $DEPLOYMENT_NAME ./manifest \
              --set django.image.repository=asia-south1-docker.pkg.dev/$PROJECT_ID/bo-main/backend \
              --set django.image.tag=$GITHUB_SHA \
              --set django.host=api-v2.integration-betteropinions.com \
              --set configMap.name=better-backend-app-config \
              --set global.environment=$ENVIRONMENT > rendered.yaml
              
      # Check release status
      - name: Check release status
        run: |
          helm status ${{ env.DEPLOYMENT_NAME }}

      # Verify Deployment
      - name: Check deployment status
        run: |
          kubectl get all --all-namespaces
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=5m || exit 1

      # Debug - Check Kubernetes resources
      - name: Debug - Check Kubernetes resources
        if: failure()
        run: |
          echo "Pods:"
          kubectl get pods
          echo "\nServices:"
          kubectl get services
          echo "\nIngresses:"
          kubectl get ingresses
          echo "\nEvents:"
          kubectl get events --sort-by=.metadata.creationTimestamp

      # Describe pods
      - name: Describe pods
        if: failure()
        run: |
          kubectl describe pods

      # Check Ingress status
      - name: Check Ingress status
        if: failure()
        run: |
          kubectl describe ingress

      # Check Helm release history
      - name: Check Helm release history
        if: failure()
        run: |
          helm history ${{ env.DEPLOYMENT_NAME }}

      # Update DNS
      - name: Update DNS
        run: |
          INGRESS_IP=$(kubectl get ingress ${{ env.DEPLOYMENT_NAME }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Updating DNS with IP: $INGRESS_IP"
          # Add your DNS update logic here
